"use client";

import { motion } from "framer-motion";
import Section from "@/components/common/Section";
import Container from "@/components/common/Container";
import Button from "@/components/common/Button";
import { Calendar, Clock, ArrowRight } from "lucide-react";
import Link from "next/link";

interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  publishedAt: string;
  readTime: string;
}

export default function BlogPreview() {
  const posts: BlogPost[] = [
    {
      slug: "optimizing-nextjs-16-rendering-systems",
      title: "Optimizing Next.js 16 Rendering Systems",
      excerpt: "Deep dive into React Server Components (RSC), server-actions caching, and dynamic partial hydration on edge routes.",
      category: "Development",
      publishedAt: "May 18, 2026",
      readTime: "5 min read",
    },
    {
      slug: "design-tokens-for-futuristic-ui-environments",
      title: "Design Tokens for Futuristic UI Environments",
      excerpt: "A guide on styling premium dark modes, structuring glassmorphism values, and configuring glow boundary metrics.",
      category: "Design",
      publishedAt: "May 10, 2026",
      readTime: "8 min read",
    },
    {
      slug: "horizontal-database-sharding-at-scale",
      title: "Horizontal Database Sharding at Scale",
      excerpt: "Analyzing postgres replication pipelines, custom connection poolers, and database latency drops under extreme load conditions.",
      category: "Architecture",
      publishedAt: "May 02, 2026",
      readTime: "12 min read",
    },
  ];

  return (
    <Section id="blog" className="border-t border-white/5 bg-[#080808]">
      <Container>
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16">
          <div className="max-w-2xl">
            <span className="text-xs uppercase tracking-widest font-semibold text-cyan-400">
              Insights & News
            </span>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight text-white mt-4">
              Zabnix Engineering Blog
            </h2>
            <p className="text-zinc-400 mt-6 leading-relaxed">
              Explore deep dives, research papers, and guides generated by our designers and systems engineers.
            </p>
          </div>
          <div className="mt-6 md:mt-0">
            <Button variant="secondary" href="#contact">
              Subscribe to Newsletter
            </Button>
          </div>
        </div>

        {/* Blog Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {posts.map((post, idx) => (
            <motion.article
              key={post.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.6, delay: idx * 0.1 }}
              className="glow-card glass-panel p-6 rounded-xl flex flex-col justify-between group"
            >
              <div>
                {/* Meta details */}
                <div className="flex items-center space-x-3 mb-6 text-[10px] text-zinc-500 font-mono uppercase tracking-wider">
                  <span className="text-cyan-400 font-bold">{post.category}</span>
                  <span>•</span>
                  <div className="flex items-center space-x-1">
                    <Calendar size={11} />
                    <span>{post.publishedAt}</span>
                  </div>
                </div>

                {/* Title */}
                <h3 className="text-lg font-bold text-white mb-4 tracking-wide group-hover:text-cyan-400 transition-colors line-clamp-2">
                  {post.title}
                </h3>
                
                {/* Excerpt */}
                <p className="text-zinc-400 text-xs md:text-sm leading-relaxed mb-6 line-clamp-3">
                  {post.excerpt}
                </p>
              </div>

              {/* Bottom detail */}
              <div className="flex items-center justify-between border-t border-white/5 pt-4 mt-6">
                <div className="flex items-center space-x-1.5 text-[10px] font-mono text-zinc-500 uppercase tracking-widest">
                  <Clock size={11} />
                  <span>{post.readTime}</span>
                </div>
                <Link href={`/blog/${post.slug}`} className="inline-flex items-center space-x-1 text-xs font-bold text-white group-hover:text-cyan-400 transition-colors">
                  <span>Read Article</span>
                  <ArrowRight size={13} className="group-hover:translate-x-1 transition-transform" />
                </Link>
              </div>
            </motion.article>
          ))}
        </div>
      </Container>
    </Section>
  );
}
